# Configuracion basica para mi proyecto de python con una pagina en django que 

#consume la api de microsoft azure cognitive.
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest



steps:
- task: AzureAppServiceSettings@1
  inputs:
    azureSubscription: 'Azure subscription 1(e8f769cd-e30b-420c-8520-8c811b4576c6)'
    appName: 'ProduccionCognitivePython'
    resourceGroupName: 'Produccion'
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
  displayName: 'Instalar Python 3.9'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Instalar dependencias'

- script: |
    python manage.py migrate
  displayName: 'Ejecutar migraciones de Django'

- script: |
    python manage.py collectstatic
  displayName: 'Recopilar archivos estáticos de Django'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(e8f769cd-e30b-420c-8520-8c811b4576c6)'
    appType: 'webAppLinux'
    WebAppName: 'ProduccionCognitive'
    deployToSlotOrASE: true
    ResourceGroupName: 'produccionGroup'
    SlotName: 'production'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    AppSettings: |
      -Port 8080 -RequestTimeout 5000
      -WEBSITE_TIME_ZONE "Eastern Standard Time"